"""Room+Word tables

Revision ID: a4db192f051f
Revises: 5e46e4ad0c14
Create Date: 2026-04-23 23:54:42.934724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4db192f051f'
down_revision: Union[str, Sequence[str], None] = '5e46e4ad0c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_in_game', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_in_game')
    # ### end Alembic commands ###
